/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '6/13/21, 4:48 PM' 
 * Generated by 'u42918662' 
 * Generated on server 'ODAWS02-APSE1.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.4.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36' 
 * Generated on web client 'https://odamid-apse1.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B03%253A00&ticket=ST-20734-vDuWacEXMV1oZ0bX4KNe-cas' 
 *
 */

data WORK.IMPORT;
	length state $ 2;
	set WORK.IMPORT;

	select (state);
		when ('WA') state='DC';
		otherwise state=state;
	end;
run;